### ISSUE TITLE
some questions about event images

### ISSUE THREAD

**Issue by booker-max** [wangxiao5791509/RGB-DVS-SOT-Baselines#1]
In your Real-Time MDNet: Dual-Modality Version, the input of the network is vis_images and event_images,  
1.    I would like to ask how this event_image is obtained？
2.     And I can't seem to find the supplementary materia for this article, can you share a copy to me? 
Thanks.

**Comment by booker-max** [comment]
Thank you very much!

**Comment by HTZhaozzZ** [comment]
Hello, I would like to ask how to get the dependency package for the Real-Time MDNet dual-modal version
