### ISSUE TITLE
Cross Modality Transformer not used during testing? 

### ISSUE THREAD

**Issue by Raphtor** [wangxiao5791509/RGB-DVS-SOT-Baselines#2]
Hello,

I am reviewing this code, and I notice in the `train.py` script, you calculate the scores of the positive and negative bounding box samples to get the class loss between them:

```
pos_score = model(pos_feats_vis, pos_feats_event, k, in_layer='fc4', useCrossAtt=True, useSelfAtt=True)    ## 512 pos samples 
neg_score = model(neg_feats_vis, neg_feats_event, k, in_layer='fc4')    ## 1568 neg samples 
```

However, during testing (in the `tracker.py` file), you call the model without `useCrossAtt=True, useSelfAtt=True`:
```
sample_scores = model(sample_feats_vis, sample_feats_event, in_layer='fc4')
```

Does this mean the CMT is not used during test time? If so, what is the purpose of it if not to aid in feature fusion?

**Comment by wsxbaaaa** [comment]
Do you understand why? I had a bad test.

**Comment by Weihua-Wang** [comment]
Hello, do you understand the reason for not using the CMT？

**Comment by Weihua-Wang** [comment]
@wangxiao5791509

**Comment by wangxiao5791509** [comment]
@Raphtor @Weihua-Wang 

Hi, thanks for your attention to this work. The CMT module combined with MDNet as a bridge between the RGB and event data. For the use of this module, of course, we can use it in the tracking phase directly. We also find that the results can be improved when only used in the training phase. For the key insight into this situation, we believe it boosts the feature interaction between the dual modalities and long-range feature mining. One can review the framework of MDNet, their FC layers for final classification in the tracking phase are also randomly initialized for each video, but the final results are good. The key lies in the domain-specific layers that help the shared feature learning of the CNN backbone network. Thus, we believe the CMT helps similarly for the final results. However, it was indeed a modest increase (not very significant) on the VisEvent dataset. More advanced improvements are welcome on this benchmark dataset. Thanks.
