### ISSUE TITLE
Excuse me , I want to know how to get the file 'VisEvent_train_subset.pkl'

### ISSUE THREAD

**Issue by zzzzyq-18** [wangxiao5791509/RGB-DVS-SOT-Baselines#4]

**Comment by wangxiao5791509** [comment]
@zzzzyq-18   please check this file: https://github.com/wangxiao5791509/RGB-DVS-SOT-Baselines/blob/main/MANet_VisEvent_master.tar.gz 

MANet_VisEvent_master\pretrain\**prepro_data.py**  
this script will generate a pkl file for each modality.
