### ISSUE TITLE
realtimeMDNet-visEvent-CMT(ALL)-python3, Train and Test

### ISSUE THREAD

**Issue by Weihua-Wang** [wangxiao5791509/RGB-DVS-SOT-Baselines#6]
pos_score = model(pos_feats_vis, pos_feats_event, k, in_layer='fc4', useCrossAtt=True, useSelfAtt=True)
neg_score = model(neg_feats_vis, neg_feats_event, k, in_layer='fc4')

Why don't neg_score go through the CMT module
And when you test, Why the code not use the CMT?

**Comment by wangxiao5791509** [comment]
@Weihua-Wang  Try new settings and test final results? Thanks.
